name: Build APK & AAB (EvasaArcJump)

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: "17"

    - name: Install Android SDK
      uses: android-actions/setup-android@v3
      with:
        packages: |
          platform-tools
          platforms;android-34
          build-tools;34.0.0

    - name: Create Android project (minimal, Kotlin)
      shell: bash
      run: |
        set -e
        mkdir -p app/src/main/java/com/evasa/arcjump
        mkdir -p app/src/main/res/values
        # local.properties so Gradle finds SDK
        echo "sdk.dir=$ANDROID_SDK_ROOT" > local.properties

        # settings.gradle
        cat > settings.gradle <<'EOF'
        rootProject.name = "EvasaArcJump"
        include ':app'
        EOF

        # root build.gradle
