name: Build APK & AAB (EvasaArcJump)

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Gradle
        run: |
          wget https://services.gradle.org/distributions/gradle-8.7-bin.zip -O gradle.zip
          unzip -q gradle.zip -d $HOME/gradle
          echo "$HOME/gradle/gradle-8.7/bin" >> $GITHUB_PATH

      - name: Build APK
        run: ./gradlew assembleDebug

      - name: Build AAB
        run: ./gradlew bundleRelease

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: EvasaArcJump-APK
          path: app/build/outputs/apk/debug/app-debug.apk

      - name: Upload AAB
        uses: actions/upload-artifact@v4
        with:
          name: EvasaArcJump-AAB
          path: app/build/outputs/bundle/release/app-release.aab
