name: Build APK & AAB (EvasaArcJump)

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ANDROID_SDK_ROOT: ${{ github.workspace }}/android-sdk

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: "17"

    - name: Install Android SDK (cmdline-tools) & packages
      shell: bash
      run: |
        set -e
        mkdir -p "$ANDROID_SDK_ROOT"
        curl -L https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip -o cmd.zip
        unzip -q cmd.zip -d "$ANDROID_SDK_ROOT/cmdline-tools"
        mv "$ANDROID_SDK_ROOT/cmdline-tools/cmdline-tools" "$ANDROID_SDK_ROOT/cmdline-tools/latest"
        yes | "$ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager" --licenses
        yes | "$ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager" "platform-tools" "platforms;android-34" "build-tools;34.0.0"
        echo "sdk.dir=$ANDROID_SDK_ROOT" > local.properties

    - name: Create minimal Android project (Kotlin)
      shell: bash
      run: |
        set -e
        mkdir -p app/src/main/java/com/evasa/arcjump
        mkdir -p app/src/main/res/values
        cat > settings.gradle <<'EOF'
        rootProject.name = "EvasaArcJump"
        include ':app'
        EOF
        cat > build.gradle <<'EOF'
        buildscript {
          ext.kotlin_version = '1.9.24'
          repositories { google(); mavenCentral() }
          dependencies {
            classpath "com.android.tools.build:gradle:8.4.1"
            classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
          }
        }
        allprojects { repositories { google(); mavenCentral() } }
        task clean(type: Delete) { delete rootProject.buildDir }
        EOF
        cat > app/build.gradle <<'EOF'
        apply plugin: 'com.android.application'
        apply plugin: 'kotlin-android'
        android {
          namespace "com.evasa.arcjump"
          compileSdk 34
          defaultConfig {
            applicationId "com.evasa.arcjump"
            minSdk 24
            targetSdk 34
            versionCode 1
            versionName "1.0.0"
          }
          buildTypes {
            release {
              minifyEnabled false
              proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'),'proguard-rules.pro'
            }
          }
        }
        dependencies {
          implementation "org.jetbrains.kotlin:kotlin-stdlib:1.9.24"
          implementation "androidx.appcompat:appcompat:1.7.0"
          implementation "androidx.core:core-ktx:1.13.1"
        }
        EOF
        echo "// default" > app/proguard-rules.pro
        cat > app/src/main/AndroidManifest.xml <<'EOF'
        <manifest xmlns:android="http://schemas.android.com/apk/res/android" package="com.evasa.arcjump">
          <application
              android:allowBackup="true"
              android:label="Evasa Arc Jump"
              android:icon="@mipmap/ic_launcher"
              android:theme="@style/Theme.EvasaArcJump">
            <activity android:name=".MainActivity" android:exported="true">
              <intent-filter>
                <action android:name="android.intent
